### ISSUE TITLE
[SEMS] Missing to tag in outgoing PRACK

### ISSUE THREAD

**Issue by denyspozniak** [sems-server/sems#100]
Hello!

We detected interesting issue with missing to tag in outgoing PRACK message (sbc application). Below you can see debug from syslog.
To header from outgoing PRACK from sems : **Jan 19 09:15:31  sems: To: \<sip:+4988888888888@10.10.10.20\>** 

```
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/sip/udp_trsp.cpp:259] DEBUG: send  msg to 185.1.1.2:5060
Jan 19 09:15:31  sems: --++--
Jan 19 09:15:31  sems: SIP/2.0 180 Ringing
Jan 19 09:15:31  sems: Via: SIP/2.0/UDP 185.1.1.2:5060;branch=z9hG4bK06Be83a26ed29c854b9
Jan 19 09:15:31  sems: From: <sip:+4977777777@185.1.1.2>;tag=gK061b7147
Jan 19 09:15:31  sems: To: <sip:+4988888888888@185.1.1.3>;tag=0DF5B399-5C42DCA300056035-E74F4700
Jan 19 09:15:31  sems: Call-ID: 872871281_120703059@185.1.1.2
Jan 19 09:15:31  sems: CSeq: 14163 INVITE
Jan 19 09:15:31  sems: Require: 100rel
Jan 19 09:15:31  sems: User-Agent: Mitel Border GW
Jan 19 09:15:31  sems: Privacy: id
Jan 19 09:15:31  sems: P-Asserted-Identity: "IVR" <sip:+888888@80.2.2.2>
Jan 19 09:15:31  sems: RSeq: 703114100
Jan 19 09:15:31  sems: Contact: <sip:185.1.1.3:5060;transport=udp>
Jan 19 09:15:31  sems: Content-Length: 0
Jan 19 09:15:31  sems: --++--


Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/sip/udp_trsp.cpp:352] DEBUG: vv M [|] u recvd msg via UDP from 185.1.1.2:5060 vv
Jan 19 09:15:31  sems: --++--
Jan 19 09:15:31  sems: PRACK sip:185.1.1.3:5060;transport=udp SIP/2.0
Jan 19 09:15:31  sems: Via: SIP/2.0/UDP 185.1.1.2:5060;branch=z9hG4bK06Be83b496c9891eec4
Jan 19 09:15:31  sems: From: <sip:+4977777777@185.1.1.2>;tag=gK061b7147
Jan 19 09:15:31  sems: To: <sip:+4988888888888@185.1.1.3>;tag=0DF5B399-5C42DCA300056035-E74F4700
Jan 19 09:15:31  sems: Call-ID: 872871281_120703059@185.1.1.2
Jan 19 09:15:31  sems: CSeq: 14164 PRACK
Jan 19 09:15:31  sems: Max-Forwards: 70
Jan 19 09:15:31  sems: RAck: 703114100 14163 INVITE
Jan 19 09:15:31  sems: Content-Length: 0
Jan 19 09:15:31  sems: --++--


Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/udp_trsp.cpp:259] DEBUG: send  msg to 10.10.10.20:5060
Jan 19 09:15:31  sems: --++--
Jan 19 09:15:31  sems: PRACK sip:10.10.10.10:5060;transport=udp SIP/2.0
Jan 19 09:15:31  sems: Via: SIP/2.0/UDP 10.10.10.30;branch=z9hG4bKuICJOaNO;rport
Jan 19 09:15:31  sems: From: <sip:+4977777777@185.1.1.3:5060>;tag=62074EBE-5C42DCA30005687D-BE9E9700
Jan 19 09:15:31  sems: To: <sip:+4988888888888@10.10.10.20>
Jan 19 09:15:31  sems: CSeq: 11 PRACK
Jan 19 09:15:31  sems: Call-ID: 872871281_120703059@185.1.1.2_isp
Jan 19 09:15:31  sems: Route: <sip:10.10.10.20:5060;lr>
Jan 19 09:15:31  sems: Max-Forwards: 69
Jan 19 09:15:31  sems: RAck: 703114100 10 INVITE
Jan 19 09:15:31  sems: Contact: <sip:10.10.10.30:5060;transport=udp>
Jan 19 09:15:31  sems: Content-Length: 0
Jan 19 09:15:31  sems: --++--

```

**Comment by denyspozniak** [comment]
Debug log before sending out PRACK, maybe it will help you.
IPs and numbers were changed, but in real this is related to last PRACK from original post.
 ```
Jan 19 09:15:31  sems: --++--
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/sip/parse_uri.cpp:338] DEBUG:  Converted URI port (5060) to int (5060)
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/sip/parse_via.cpp:521] DEBUG:  parsed branch: z9hG4bK06Be83b496c9891eec4
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/sip/parse_via.cpp:544] DEBUG:  has_rport: 0
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/sip/parse_100rel.cpp:108] DEBUG:  parsed 'RSeq' header: 703114100 14163 <14163> <INVITE>.
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/sip/trans_table.cpp:99] DEBUG:  Matching PRACK request
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/sip/trans_table.cpp:363] DEBUG:  Matching PRACK request
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:765] DEBUG:  Received new request from <185.1.1.2:5060/udp> on intf #0
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:769] DEBUG:  req.method = <PRACK>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:772] DEBUG:  req.r_uri = <sip:185.1.1.3:5060;transport=udp>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:773] DEBUG:  req.from_uri = <sip:+4977777777@185.1.1.2>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:774] DEBUG:  req.from = <<sip:+4977777777@185.1.1.2>>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:775] DEBUG:  req.to = <<sip:+4988888888888@185.1.1.3>;tag=0DF5B399-5C42DCA300056035-E74F4700>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:776] DEBUG:  req.callid = <872871281_120703059@185.1.1.2>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:777] DEBUG:  req.from_tag = <gK061b7147>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:778] DEBUG:  req.to_tag = <0DF5B399-5C42DCA300056035-E74F4700>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:779] DEBUG:  cseq = <14164>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:780] DEBUG:  max_forwards = <70>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:781] DEBUG:  req.route = <>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:782] DEBUG:  hdrs = <>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:783] DEBUG:  body-ct = <>
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/AmEventQueue.cpp:54] DEBUG:  AmEventQueue: trying to post event
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/AmEventQueue.cpp:70] DEBUG:  AmEventQueue: event posted
Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/SipCtrlInterface.cpp:789] DEBUG:  ^^ M [872871281_120703059@185.1.1.2|0DF5B399-5C42DCA300056035-E74F4700] Ru SIP request PRACK handled ^^
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmSession.cpp:347] DEBUG:  vv S [872871281_120703059@185.1.1.2|0DF5B399-5C42DCA300056035-E74F4700] Early, running, 0 UACTransPending, 0 usages vv
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmEventQueue.cpp:85] DEBUG:  before processing event (17AmSipRequestEvent)
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmSession.cpp:650] DEBUG:  AmSession processing event
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmBasicSipDialog.cpp:326] DEBUG:  AmBasicSipDialog::onRxRequest(req = PRACK)
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/apps/sbc/CallLeg.cpp:929] DEBUG:  0DF5B399-5C42DCA300056035-E74F4700: SIP request 14164 PRACK received in Ringing state
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmB2BSession.cpp:356] DEBUG:  relaying B2B SIP request (fwd) PRACK sip:185.1.1.3:5060;transport=udp
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/apps/sbc/SBCCallLeg.cpp:437] DEBUG:  filtering body for request 'PRACK' (c/t '')
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/apps/sbc/SBCCallLeg.cpp:1427] DEBUG:  filtering body
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmB2BSession.cpp:591] DEBUG:  AmB2BSession::relayEvent: to other_id='62074EBE-5C42DCA30005687D-BE9E9700'
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmEventQueue.cpp:54] DEBUG:  AmEventQueue: trying to post event
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmEventQueue.cpp:70] DEBUG:  AmEventQueue: event posted
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmEventQueue.cpp:89] DEBUG:  event processed (17AmSipRequestEvent)
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/AmSession.cpp:347] DEBUG:  vv S [872871281_120703059@185.1.1.2_isp|62074EBE-5C42DCA30005687D-BE9E9700] Proceeding, running, 1 UACTransPending, 0 usages vv
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/AmEventQueue.cpp:85] DEBUG:  before processing event (18B2BSipRequestEvent)
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/AmB2BSession.cpp:176] DEBUG:  AmB2BSession::onB2BEvent
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/AmB2BSession.cpp:186] DEBUG:  B2BSipRequest: PRACK (fwd=true)
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/AmB2BSession.cpp:805] DEBUG:  relaying SIP request PRACK sip:185.1.1.3:5060;transport=udp 69
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/AmBasicSipDialog.cpp:120] DEBUG:  [62074EBE-5C42DCA30005687D-BE9E9700] resulting Contact header: <sip:10.10.10.10:5060>
Jan 19 09:15:31  sems: [3969//builddir/build/BUILD/sems-1.7.1/core/AmSession.cpp:366] DEBUG:  ^^ S [872871281_120703059@185.1.1.2|0DF5B399-5C42DCA300056035-E74F4700] Early, running, 0 UACTransPending, 0 usages ^^
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/parse_uri.cpp:338] DEBUG:  Converted URI port (5060) to int (5060)
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/trans_layer.cpp:924] DEBUG:  no transport specified, setting default one (udp)
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/trans_layer.cpp:931] DEBUG:  next_hop:next_port is <10.10.10.20:5060/udp>
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/resolver.cpp:1080] DEBUG:  sip_destination: 10.10.10.20:5060/udp
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/resolver.cpp:1005] DEBUG:  checking whether '10.10.10.20' is IP address...
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/resolver.cpp:1063] DEBUG:  set destination to 10.10.10.20:5060
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/resolver.cpp:794] DEBUG:  target list:
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/resolver.cpp:801] DEBUG:  #01110.10.10.20:5060/udp to target list
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/trans_layer.cpp:1267] DEBUG:  send_request to R-URI <sip:10.10.10.30:5060;transport=udp>
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/trans_layer.cpp:160] DEBUG:  contact: <<sip:10.10.10.10:5060>>
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/parse_uri.cpp:338] DEBUG:  Converted URI port (5060) to int (5060)
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/parse_uri.cpp:338] DEBUG:  Converted URI port (5060) to int (5060)
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/parse_via.cpp:521] DEBUG:  parsed branch: z9hG4bKuICJOaNO
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/parse_via.cpp:544] DEBUG:  has_rport: 1
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/parse_100rel.cpp:108] DEBUG:  parsed 'RSeq' header: 703114100 10 <10> <INVITE>.
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/trans_layer.cpp:1303] DEBUG:  Sending to 10.10.10.20:5060 <PRACK sip:10.10.10.30:5060;transport=udp SIP/2.0
Jan 19 09:15:31  sems: Via: SIP/2.0/UDP 10.10.10.10;branch=z9hG4bKuICJOaNO;rport
Jan 19 09:15:31  sems: From: <sip:+4977777777@185.1.1.3:5060>;tag=62074EBE-5C42DCA30005687D-BE9E9700
Jan 19 09:15:31  sems: To: <sip:+4988888888888@10.10.10.20>
Jan 19 09:15:31  sems: CSeq: 11 PRACK
Jan 19 09:15:31  sems: Call-ID: 872871281_120703059@185.1.1.2_isp
Jan 19 09:15:31  sems: Route: <sip:10.10.10.20:5060;lr>
Jan 19 09:15:31  sems: Max-Forwards: 69
Jan 19 09:15:31  sems: RAck: 703114100 10 INVITE
Jan 19 09:15:31  sems: Contact: <sip:10.10.10.10:5060;transport=udp>
Jan 19 09:15:31  sems: Content-Length: 0
Jan 19 09:15:31  sems: ...>
Jan 19 09:15:31  sems: [3970//builddir/build/BUILD/sems-1.7.1/core/sip/udp_trsp.cpp:259] DEBUG: send  msg to 10.10.10.20:5060
Jan 19 09:15:31  sems: --++--
Jan 19 09:15:31  sems: PRACK sip:10.10.10.30:5060;transport=udp SIP/2.0
Jan 19 09:15:31  sems: Via: SIP/2.0/UDP 10.10.10.10;branch=z9hG4bKuICJOaNO;rport
Jan 19 09:15:31  sems: From: <sip:+4977777777@185.1.1.3:5060>;tag=62074EBE-5C42DCA30005687D-BE9E9700
Jan 19 09:15:31  sems: To: <sip:+4988888888888@10.10.10.20>
Jan 19 09:15:31  sems: CSeq: 11 PRACK
Jan 19 09:15:31  sems: Call-ID: 872871281_120703059@185.1.1.2_isp
Jan 19 09:15:31  sems: Route: <sip:10.10.10.20:5060;lr>
Jan 19 09:15:31  sems: Max-Forwards: 69
Jan 19 09:15:31  sems: RAck: 703114100 10 INVITE
Jan 19 09:15:31  sems: Contact: <sip:10.10.10.10:5060;transport=udp>
Jan 19 09:15:31  sems: Content-Length: 0
Jan 19 09:15:31  sems: --++--


````

**Comment by juha-h** [comment]
denyspozniak writes:

> We detected interesting issue with missing to tag in outgoing PRACK message (sbc application). Below you can see debug from syslog.
> To header from outgoing PRACK from sems : **Jan 19 09:15:31  sems: To: \<sip:+4988888888888@10.10.10.20\>**

I don't have a PRACK capable SIP UA to test this.  Use TCP instead of
UDP and you don't need PRACK.

> Jan 19 09:15:31  sems: [12037//builddir/build/BUILD/sems-1.7.1/core/sip/udp_trsp.cpp:352] DEBUG: vv M [|] u recvd msg via UDP from 185.1.1.2:5060 vv
> Jan 19 09:15:31  sems: --++--
> Jan 19 09:15:31  sems: PRACK sip:185.1.1.3:5060;transport=udp SIP/2.0

> Also one note to the previous message.
> SEMS 1.7 does not add $rU to the PRACK, but SEMS 1.6 does.

Received PRACK in above does not have $rU.

**Comment by denyspozniak** [comment]
Hello!

We are using SEMS as intermediate node between providers, so supporting PRACK is mandatory for us.
Interesting that old sems version (~2 years old) works well with PRACK (but we have another issue with zombie calls I reported before), so issue is only with last master. Maybe it helps you, but as experiment I tested sipwise sems mr7 (https://hub.docker.com/r/sipwise/mr7.0.1) and they do not have PRACK issue (but have issue with content length duplication :) ).
I can help you to build environment for testing (FreeSWITCH + sipp scenario).

Yes, currently incoming PRACK does not have $rU, but outgoing yes. I can send you direct pcap trace and sbcprofile, or even can share screen via teamviewer. But anyway outgoing $rU is not critical as totag.

Thanks!

**Comment by juha-h** [comment]
Try with this patch:

diff --git a/core/AmSipDialog.cpp b/core/AmSipDialog.cpp
index 39ff2aa6..4040f90b 100644
--- a/core/AmSipDialog.cpp
+++ b/core/AmSipDialog.cpp
@@ -366,8 +366,7 @@ bool AmSipDialog::onRxReplyStatus(const AmSipReply& reply)
       if(reply.code < 200){
    // Do not go to Early state if To tag can still change
    // Otherwise reply check will fail
-   if (((reply.code == 100) ||
-        ((reply.code >= 180) && (reply.code <= 183)))
+   if (((reply.code == 100) || (reply.code == 181) || (reply.code == 182))
        || reply.to_tag.empty())
      setStatus(Proceeding);
    else {

It reverts an earlier commit.

**Comment by denyspozniak** [comment]
Hello!
Issue is fixed! Thanks!
Outgoing PRACK has to tag:

![image](https://user-images.githubusercontent.com/22612345/51899811-7711f480-23bc-11e9-9232-453e4628db46.png)

**Comment by juha-h** [comment]
denyspozniak writes:

> Issue is fixed! Thanks!

It is not fixed.  The patch broke normal 1xx (xx > 80) response
processing by handling only the first one.  In the mean time, I worked
on a real fix (below).  Could you give it a try?  It worked in my
tests.
```
diff --git a/core/AmSipDialog.cpp b/core/AmSipDialog.cpp
index 39ff2aa6..e34274a7 100644
--- a/core/AmSipDialog.cpp
+++ b/core/AmSipDialog.cpp
@@ -339,11 +339,13 @@ bool AmSipDialog::onRxReplySanity(const AmSipReply& reply)
 
     if(status == Early) {
       if(reply.code < 200 && !reply.to_tag.empty()) {
-        return false;// DROP
+	// Provision reply, such as 180, can come from a new UAS
+	return true;
       }
     }
     else {
-      // DROP
+      DBG("dropping reply (%u %s) in non-Early state\n",
+	  reply.code, reply.reason.c_str());
       return false;
     }
   }
@@ -364,10 +366,8 @@ bool AmSipDialog::onRxReplyStatus(const AmSipReply& reply)
     case Trying:
     case Proceeding:
       if(reply.code < 200){
-	// Do not go to Early state if To tag can still change
-	// Otherwise reply check will fail
-	if (((reply.code == 100) ||
-	     ((reply.code >= 180) && (reply.code <= 183)))
+	// Do not go to Early state if reply did not come from an UAS
+	if (((reply.code == 100) || (reply.code == 181) || (reply.code == 182))
 	    || reply.to_tag.empty())
 	  setStatus(Proceeding);
 	else {
@@ -399,8 +399,16 @@ bool AmSipDialog::onRxReplyStatus(const AmSipReply& reply)
 
     case Early:
       if(reply.code < 200){
-        DBG("ignoring provisional reply in Early state");
+	if (!reply.to_tag.empty() && (reply.to_tag != getRemoteTag())) {
+	  DBG("updating dialog based on reply (%u %s) in Early state\n",
+	      reply.code, reply.reason.c_str());
+	  setRemoteTag(reply.to_tag);
+	  setRouteSet(reply.route);
+	  break;
+	} 
         //DROP!!!
+	DBG("ignoring provisional reply (%u %s) in Early state\n",
+	    reply.code, reply.reason.c_str());
       }
       else if(reply.code < 300){
 	setStatus(Connected);
```

**Comment by denyspozniak** [comment]
Hello! I tested many scenarios, looks working.

**Comment by juha-h** [comment]
denyspozniak writes:

> Hello! I tested many scenarios, looks working.

Thanks for reporting and testing.  I just committed the changes.

**Comment by juha-h** [comment]
Fixed by commit 96ea4423d08a4185469b97fcef3b6cead9666ce6

**Comment by denyspozniak** [comment]
Thank you too!
