### ISSUE TITLE
sbc module has unresolved symbols on Fedora

### ISSUE THREAD

**Issue by mtremer** [sems-server/sems#20]
The sems package shipped with Fedora comes with a broken sbc.so module. When sems tries to load that the following error occurs:

Sep 07 23:59:02 XXX sems[31868]: [/builddir/build/BUILD/sems-1.6.0/core/AmPlugIn.cpp:298] ERROR:  AmPlugIn::loadPlugIn: /usr/lib64/sems/plug-in//sbc.so: /usr/lib64/sems/plug-in//sbc.so: undefined symbol: _ZTI14_RegisterCache
Sep 07 23:59:02 XXX sems[31868]: [/builddir/build/BUILD/sems-1.6.0/core/AmPlugIn.cpp:206] ERROR:  while loading plug-in '/usr/lib64/sems/plug-in//sbc.so'

I opened a bug report on the Fedora bugtracker, too: https://bugzilla.redhat.com/show_bug.cgi?id=1260803

This does not seem to be an issue with the Fedora buildsystem though.

**Comment by dunst0** [comment]
The binary build from epel doesn't work on CentOS 7 as well with the same error.
But build from source works fine.

**Comment by lemenkov** [comment]
This was indeed an issue with cmake buildsystem. I've fixed it.

**Comment by 46labs** [comment]
@lemenkov have you pushed this fix to master, if so...its still failing?

**Comment by alochym01** [comment]
i did get same error as 46labs when compile sems from github to test opus codec with sems and i switch to sipwise github and it working fine
https://github.com/sipwise/sems

if you use Centos you can enable epel-testing it also works https://github.com/sems-server/sems/issues/31

**Comment by lemenkov** [comment]
@46labs sorry for the delay - just made a pull-request.

**Comment by 46labs** [comment]
@lemenkov hey, no worries. Thanks for your help!
